export default {
    //木２種類（通れる木と通れない木）
    //黒い背景も二種類（通れるのと通れないの）
    C: { id: "C", label: "山", img: "C.png", isBlock: false },
    D: { id: "D", label: "土", img: "D.png", isBlock: false },
    E: { id: "E", label: "城下町の床", img: "E.png", isBlock: false },
    F: { id: "F", label: "焚火", img: "F.png", isBlock: true },
    G: { id: "G", label: "城中床", img: "G.png", isBlock: false },
    H: { id: "H", label: "城中床外枠", img: "H.png", isBlock: false },
    I: { id: "I", label: "地下階段", img: "I.png", isBlock: false },
    J: { id: "J", label: "家床", img: "J.png", isBlock: false },
    K: { id: "K", label: "王座への階段", img: "K.png", isBlock: false },
    L: { id: "L", label: "王座", img: "L.png", isBlock: true },
    M: { id: "M", label: "家パーツ（左上）", img: "M.png", isBlock: true },
    N: { id: "N", label: "家パーツ（真ん中上）", img: "N.png", isBlock: true },
    O: { id: "O", label: "家パーツ（右上）", img: "O.png", isBlock: true },
    P: { id: "P", label: "家パーツ（左上から二段下）", img: "P.png", isBlock: true },
    Q: { id: "Q", label: "家パーツ（真ん中から二段下）", img: "Q.png", isBlock: true },
    R: { id: "R", label: "家パーツ（右上から二段下）", img: "R.png", isBlock: true },
    S: { id: "S", label: "家パーツ（左上から三段下）", img: "S.png", isBlock: true },
    T: { id: "T", label: "家パーツ（真ん中上から三段下）", img: "T.png", isBlock: true },
    U: { id: "U", label: "家パーツ（右上から三段下）", img: "U.png", isBlock: true },
    V: { id: "V", label: "家パーツ（左右下）", img: "V.png", isBlock: true },
    W: { id: "W", label: "家パーツ（真ん中下）", img: "W.png", isBlock: false },
    X: { id: "X", label: "地下水", img: "X.png", isBlock: true },
    Y: { id: "Y", label: "森パーツ（下）", img: "Y.png", isBlock: false },
    Z: { id: "Z", label: "森パーツ（上）", img: "Z.png", isBlock: false },
    
    a: { id: "a", label: "木（通れない）", img: "B.png", isBlock: true },

    aa: { id: "aa", label: "草原", img: "aa.png", isBlock: false },
    ab: { id: "ab", label: "木（通れる）", img: "ab.png", isBlock: false },
    ac: { id: "ac", label: "木（通れない）", img: "ac.png", isBlock: true },
    ad: { id: "ad", label: "", img: "ad.png", isBlock: false },
    ae: { id: "ae", label: "", img: "ae.png", isBlock: false },
    af: { id: "af", label: "", img: "af.png", isBlock: false },
    ag: { id: "ag", label: "", img: "ag.png", isBlock: false },
    ah: { id: "ah", label: "", img: "ah.png", isBlock: false },
    ai: { id: "ai", label: "", img: "ai.png", isBlock: false },
    aj: { id: "aj", label: "", img: "aj.png", isBlock: false },
    ak: { id: "ak", label: "", img: "ak.png", isBlock: false },
    al: { id: "al", label: "", img: "al.png", isBlock: false },
    am: { id: "am", label: "", img: "am.png", isBlock: false },
    an: { id: "an", label: "", img: "an.png", isBlock: false },
    ao: { id: "ao", label: "", img: "ao.png", isBlock: false },
    ap: { id: "ap", label: "", img: "ap.png", isBlock: false },
    aq: { id: "aq", label: "", img: "aq.png", isBlock: false },
    ar: { id: "ar", label: "", img: "ar.png", isBlock: false },
    as: { id: "as", label: "", img: "as.png", isBlock: false },
    at: { id: "at", label: "", img: "at.png", isBlock: false },
    au: { id: "au", label: "", img: "au.png", isBlock: false },
    av: { id: "av", label: "", img: "av.png", isBlock: false },
    aw: { id: "aw", label: "", img: "aw.png", isBlock: false },
    ax: { id: "ax", label: "", img: "ax.png", isBlock: false },
    ay: { id: "ay", label: "", img: "ay.png", isBlock: false },
    az: { id: "az", label: "", img: "az.png", isBlock: false },
    ba: { id: "ba", label: "", img: "ba.png", isBlock: false },
    bb: { id: "bb", label: "", img: "bb.png", isBlock: false },
    bc: { id: "bc", label: "", img: "bc.png", isBlock: false },
    bd: { id: "bd", label: "", img: "bd.png", isBlock: false },
    be: { id: "be", label: "", img: "be.png", isBlock: false },
    bf: { id: "bf", label: "", img: "bf.png", isBlock: false },
    bg: { id: "bg", label: "", img: "bg.png", isBlock: false },
    bh: { id: "bh", label: "", img: "bh.png", isBlock: false },
    bi: { id: "bi", label: "", img: "bi.png", isBlock: false },
    bj: { id: "bj", label: "", img: "bj.png", isBlock: false },
    bk: { id: "bk", label: "", img: "bk.png", isBlock: false },
    bl: { id: "bl", label: "", img: "bl.png", isBlock: false },
    bm: { id: "bm", label: "", img: "bm.png", isBlock: false },
    bn: { id: "bn", label: "", img: "bn.png", isBlock: false },
    bo: { id: "bo", label: "", img: "bo.png", isBlock: false },
    bp: { id: "bp", label: "", img: "bp.png", isBlock: false },
    bq: { id: "bq", label: "", img: "bq.png", isBlock: false },
    br: { id: "br", label: "", img: "br.png", isBlock: false },
    bs: { id: "bs", label: "", img: "bs.png", isBlock: false },
    bt: { id: "bt", label: "", img: "bt.png", isBlock: false },
    bu: { id: "bu", label: "", img: "bu.png", isBlock: false },
    bv: { id: "bv", label: "", img: "bv.png", isBlock: false },
    bw: { id: "bw", label: "", img: "bw.png", isBlock: false },
    bx: { id: "bx", label: "", img: "bx.png", isBlock: false },
    by: { id: "by", label: "", img: "by.png", isBlock: false },
    bz: { id: "bz", label: "", img: "bz.png", isBlock: false },
    ca: { id: "ca", label: "", img: "ca.png", isBlock: false },
    cb: { id: "cb", label: "", img: "cb.png", isBlock: false },
    cc: { id: "cc", label: "", img: "cc.png", isBlock: false },
    cd: { id: "cd", label: "", img: "cd.png", isBlock: false },
    ce: { id: "ce", label: "", img: "ce.png", isBlock: false },
    cf: { id: "cf", label: "", img: "cf.png", isBlock: false },
    cg: { id: "cg", label: "", img: "cg.png", isBlock: false },
    ch: { id: "ch", label: "", img: "ch.png", isBlock: false },
    ci: { id: "ci", label: "", img: "ci.png", isBlock: false },
    cj: { id: "cj", label: "", img: "cj.png", isBlock: false },
    ck: { id: "ck", label: "", img: "ck.png", isBlock: false },
    cl: { id: "cl", label: "", img: "cl.png", isBlock: false },
    cm: { id: "cm", label: "", img: "cm.png", isBlock: false },
    cn: { id: "cn", label: "", img: "cn.png", isBlock: false },
    co: { id: "co", label: "", img: "co.png", isBlock: false },
    // cp: { id: "cp", label: "", img: "cp.png", isBlock: false },
    // cq: { id: "cq", label: "", img: "cq.png", isBlock: false },
    // cr: { id: "cr", label: "", img: "cr.png", isBlock: false },
    // cs: { id: "cs", label: "", img: "cs.png", isBlock: false },
    // ct: { id: "ct", label: "", img: "ct.png", isBlock: false },
    // cu: { id: "cu", label: "", img: "cu.png", isBlock: false },
    // cv: { id: "cv", label: "", img: "cv.png", isBlock: false },
    // cw: { id: "cw", label: "", img: "cw.png", isBlock: false },
    // cx: { id: "cx", label: "", img: "cx.png", isBlock: false },
    // cy: { id: "cy", label: "", img: "cy.png", isBlock: false },
    // cz: { id: "cz", label: "", img: "cz.png", isBlock: false },

}

