export default {
    //木２種類（通れる木と通れない木）
    //黒い背景も二種類（通れるのと通れないの）

    aa: { id: "aa", label: "草原", img: "aa.png", isBlock: false },
    ab: { id: "ab", label: "森（上）", img: "ab.png", isBlock: true },
    ac: { id: "ac", label: "森（中）", img: "ac.png", isBlock: true },
    ad: { id: "ad", label: "森（下）", img: "ad.png", isBlock: true },
    ae: { id: "ae", label: "焚火", img: "ae.png", isBlock: false },
    af: { id: "af", label: "木", img: "af.png", isBlock: false },
    ag: { id: "ag", label: "山", img: "ag.png", isBlock: false },
    ah: { id: "ah", label: "土", img: "ah.png", isBlock: false },
    ai: { id: "ai", label: "城下町床", img: "ai.png", isBlock: false },
    aj: { id: "aj", label: "カーペット", img: "aj.png", isBlock: false },
    ak: { id: "ak", label: "タイル", img: "ak.png", isBlock: false },
    al: { id: "al", label: "階段", img: "al.png", isBlock: false },
    am: { id: "am", label: "木の床", img: "am.png", isBlock: false },
    an: { id: "an", label: "王座階段", img: "an.png", isBlock: false },
    ao: { id: "ao", label: "王座", img: "ao.png", isBlock: false },
    ap: { id: "ap", label: "家パーツ(1)", img: "ap.png", isBlock: true },
    aq: { id: "aq", label: "家パーツ(2)", img: "aq.png", isBlock: true },
    ar: { id: "ar", label: "家パーツ(3)", img: "ar.png", isBlock: true },
    as: { id: "as", label: "家パーツ(4)", img: "as.png", isBlock: true },
    at: { id: "at", label: "家パーツ(5)", img: "at.png", isBlock: true },
    au: { id: "au", label: "家パーツ(6)", img: "au.png", isBlock: true },
    av: { id: "av", label: "家パーツ(7)", img: "av.png", isBlock: true },
    aw: { id: "aw", label: "家パーツ(8)", img: "aw.png", isBlock: true },
    ax: { id: "ax", label: "家パーツ(10)", img: "ax.png", isBlock: true },
    ay: { id: "ay", label: "家パーツ(11)", img: "ay.png", isBlock: true },
    az: { id: "az", label: "家（ドア）", img: "az.png", isBlock: false },
    ba: { id: "ba", label: "unknown", img: "ba.png", isBlock: true },
    bb: { id: "bb", label: "unknown", img: "bb.png", isBlock: true },
    bc: { id: "bc", label: "銅像(下)", img: "bc.png", isBlock: true },
    bd: { id: "bd", label: "銅像(上)", img: "bd.png", isBlock: true },
    be: { id: "be", label: "ポスト", img: "be.png", isBlock: false },
    bf: { id: "bf", label: "掲示板", img: "bf.png", isBlock: true },
    bg: { id: "bg", label: "看板(アイテム)", img: "bg.png", isBlock: false },
    bh: { id: "bh", label: "看板(宿)", img: "bh.png", isBlock: false },
    bi: { id: "bi", label: "看板(武器屋)", img: "bi.png", isBlock: false },
    bj: { id: "bj", label: "WM(村)", img: "bj.png", isBlock: false },
    bk: { id: "bk", label: "地下室パーツ(壁上)", img: "bk.png", isBlock: false },
    bl: { id: "bl", label: "地下室パーツ(壁)", img: "bl.png", isBlock: false },
    bm: { id: "bm", label: "地下室パーツ(床角)", img: "bm.png", isBlock: false },
    bn: { id: "bn", label: "地下室パーツ(床)", img: "bn.png", isBlock: false },
    bo: { id: "bo", label: "魔法陣", img: "bo.png", isBlock: false },
    bp: { id: "bp", label: "木造家パーツ(1)", img: "bp.png", isBlock: false },
    bq: { id: "bq", label: "木造家パーツ(2)", img: "bq.png", isBlock: false },
    br: { id: "br", label: "木造家パーツ(3)", img: "br.png", isBlock: false },
    bs: { id: "bs", label: "木造家パーツ(4)", img: "bs.png", isBlock: false },
    bt: { id: "bt", label: "木造家パーツ(5)", img: "bt.png", isBlock: false },
    bu: { id: "bu", label: "木造家パーツ(6)", img: "bu.png", isBlock: false },
    bv: { id: "bv", label: "木造家パーツ(7)", img: "bv.png", isBlock: false },
    bw: { id: "bw", label: "木造家パーツ(8)", img: "bw.png", isBlock: false },
    bx: { id: "bx", label: "木造家パーツ(9)", img: "bx.png", isBlock: false },
    by: { id: "by", label: "木造家パーツ(10)", img: "by.png", isBlock: false },
    bz: { id: "bz", label: "木造家パーツ(ドア)", img: "bz.png", isBlock: false },
    ca: { id: "ca", label: "木造家パーツ(11)", img: "ca.png", isBlock: false },
    cb: { id: "cb", label: "柵パーツ(1)", img: "cb.png", isBlock: false },
    cc: { id: "cc", label: "柵パーツ(2)", img: "cc.png", isBlock: false },
    cd: { id: "cd", label: "柵パーツ(3)", img: "cd.png", isBlock: false },
    ce: { id: "ce", label: "柵パーツ(4)", img: "ce.png", isBlock: false },
    cf: { id: "cf", label: "柵パーツ(5)", img: "cf.png", isBlock: false },
    cg: { id: "cg", label: "柵パーツ(6)", img: "cg.png", isBlock: false },
    ch: { id: "ch", label: "井戸", img: "ch.png", isBlock: false },
    ci: { id: "ci", label: "路地裏(壁)", img: "ci.png", isBlock: true },
    cj: { id: "cj", label: "黒", img: "cj.png", isBlock: false },
    ck: { id: "ck", label: "路地裏(オブジェクト)", img: "ck.png", isBlock: false },
    cl: { id: "cl", label: "木箱パーツ(1)", img: "cl.png", isBlock: false },
    cm: { id: "cm", label: "木箱パーツ(2)", img: "cm.png", isBlock: false },
    cn: { id: "cn", label: "木箱パーツ(3)", img: "cn.png", isBlock: false },
    co: { id: "co", label: "木箱パーツ(4)", img: "co.png", isBlock: false },
    // cp: { id: "cp", label: "", img: "cp.png", isBlock: false },
    // cq: { id: "cq", label: "", img: "cq.png", isBlock: false },
    // cr: { id: "cr", label: "", img: "cr.png", isBlock: false },
    // cs: { id: "cs", label: "", img: "cs.png", isBlock: false },
    // ct: { id: "ct", label: "", img: "ct.png", isBlock: false },
    // cu: { id: "cu", label: "", img: "cu.png", isBlock: false },
    // cv: { id: "cv", label: "", img: "cv.png", isBlock: false },
    // cw: { id: "cw", label: "", img: "cw.png", isBlock: false },
    // cx: { id: "cx", label: "", img: "cx.png", isBlock: false },
    // cy: { id: "cy", label: "", img: "cy.png", isBlock: false },
    // cz: { id: "cz", label: "", img: "cz.png", isBlock: false },

}

