export default {
    images: [
        "AAAAAAAAAAAAAAEEEEAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAEEEEAAAAAAAAAAAAAA",
        "AAAMNOAMNOAMNOEEEEMNOAMNOAMNOAAA",
        "AAAPQRAPQRAPQREEEEPQRAPQRAPQRAAA",
        "AAASTUASTUASTUEEEESTUASTUASTUAAA",
        "AAAVWVAVWVAVWVEEEEVWVAVWVAVWVAAA",
        "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
        "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
        "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
        "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
        "AAAMNOAMNOAMNOEEEEMNOAMNOAMNOAAA",
        "AAAPQRAPQRAPQREEEEPQRAPQRAPQRAAA",
        "AAASTUASTUASTUEEEESTUASTUASTUAAA",
        "AAAVWVAVWVAVWVEEEEVWVAVWVAVWVAAA",
        "AAAAAAAAAAAAAAEEEEAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAEEEEAAAAAAAAAAAAAA",
        
    ],

    sounds: {
        bgm: {
            id: "world"
        }        
    },
    events: [
        {
            x: 0, y: 0, 
            goto: { name: "world", x: 5, y: 6 }
        }
    ],
}